
if("${CMAKE_SYSTEM_NAME}" STREQUAL Linux)
  set(LINUX TRUE)
endif()

if(MINGW)
  set(OPENMODELICA_ARCH "mingw64")
elseif(WIN32)
  set(OPENMODELICA_ARCH "win64"  )
elseif(LINUX)
  set(OPENMODELICA_ARCH "linux64")
endif()

if(NOT DEFINED OPENMODELICA_RESOURCES_DIR)
  set(OPENMODELICA_RESOURCES_DIR
    ${PROJECT_SOURCE_DIR}
    )
endif()

set(OPENMODELICA_LIBRARY_DIR
  ${OPENMODELICA_RESOURCES_DIR}/Library/${OPENMODELICA_ARCH}/
  )
